-- Migration 034: Create Platform Revenue Ledger
-- Date: 2026-04-11
-- Purpose: Track ALL revenue generated by platform (70% revenue focus)
-- Target: $23K/month by Month 12, scaling to $230K/month by Month 24

-- Platform Revenue Ledger (Master record of ALL revenue)
CREATE TABLE IF NOT EXISTS platform_revenue_ledger (
  id SERIAL PRIMARY KEY,

  -- Revenue Source
  revenue_source VARCHAR(60) NOT NULL, -- barter_transaction_fees / labor_transaction_fees / verification_fees / escrow_fees / premium_listing_fees / facility_commissions / pharmacy_order_commissions / currency_conversion_fees

  -- Amount
  amount_ugx DOUBLE PRECISION NOT NULL,
  amount_ap INTEGER, -- If revenue was in Afya Points
  amount_local_currency DOUBLE PRECISION, -- If revenue was in local currency (NGN, KES, ZAR)
  local_currency_code VARCHAR(5),

  -- Transaction Reference
  user_id INTEGER, -- User who paid the fee
  transaction_id INTEGER, -- Reference to the transaction that generated revenue
  transaction_type VARCHAR(40), -- barter_exchange / labor_booking / pharmacy_order / facility_service

  -- Revenue Attribution
  country_code VARCHAR(5), -- Which country generated this revenue
  facility_id INTEGER, -- If facility/pharmacy commission
  partner_revenue_share_ugx DOUBLE PRECISION, -- Partner's share of revenue (if applicable)

  -- Date
  revenue_date DATE NOT NULL,
  month DATE NOT NULL, -- YYYY-MM-01 for aggregation
  quarter VARCHAR(10), -- Q1 2026, Q2 2026, etc.
  year INTEGER,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (country_code) REFERENCES countries_supported(country_code),
  FOREIGN KEY (facility_id) REFERENCES facility_partners(id) ON DELETE SET NULL
);

-- Monthly Revenue Summary (Aggregated by month and source)
CREATE TABLE IF NOT EXISTS monthly_revenue_summary (
  id SERIAL PRIMARY KEY,
  month DATE NOT NULL, -- YYYY-MM-01

  -- Revenue by Source
  barter_fees_ugx DOUBLE PRECISION DEFAULT 0,
  labor_fees_ugx DOUBLE PRECISION DEFAULT 0,
  verification_fees_ugx DOUBLE PRECISION DEFAULT 0,
  escrow_fees_ugx DOUBLE PRECISION DEFAULT 0,
  premium_listing_fees_ugx DOUBLE PRECISION DEFAULT 0,
  facility_commissions_ugx DOUBLE PRECISION DEFAULT 0,
  pharmacy_commissions_ugx DOUBLE PRECISION DEFAULT 0,
  currency_conversion_fees_ugx DOUBLE PRECISION DEFAULT 0,

  -- Total
  total_revenue_ugx DOUBLE PRECISION DEFAULT 0,
  total_revenue_usd DOUBLE PRECISION, -- Converted to USD for reporting

  -- Transaction Counts
  total_transactions INTEGER DEFAULT 0,
  barter_transactions INTEGER DEFAULT 0,
  labor_transactions INTEGER DEFAULT 0,
  pharmacy_orders INTEGER DEFAULT 0,
  facility_services INTEGER DEFAULT 0,

  -- Revenue per Transaction (KPI)
  avg_revenue_per_transaction_ugx DOUBLE PRECISION,

  -- Country Breakdown (Top 5 countries by revenue)
  top_country_1_code VARCHAR(5),
  top_country_1_revenue_ugx DOUBLE PRECISION,
  top_country_2_code VARCHAR(5),
  top_country_2_revenue_ugx DOUBLE PRECISION,
  top_country_3_code VARCHAR(5),
  top_country_3_revenue_ugx DOUBLE PRECISION,

  calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (month)
);

-- Country Revenue Summary (Revenue by country by month)
CREATE TABLE IF NOT EXISTS country_revenue_summary (
  id SERIAL PRIMARY KEY,
  country_code VARCHAR(5) NOT NULL,
  month DATE NOT NULL,

  total_revenue_ugx DOUBLE PRECISION DEFAULT 0,
  total_revenue_local_currency DOUBLE PRECISION DEFAULT 0,
  local_currency_code VARCHAR(5),

  barter_fees_ugx DOUBLE PRECISION DEFAULT 0,
  labor_fees_ugx DOUBLE PRECISION DEFAULT 0,
  total_transactions INTEGER DEFAULT 0,

  -- User Metrics
  active_users INTEGER DEFAULT 0, -- Users who transacted this month
  new_users INTEGER DEFAULT 0, -- First-time users this month

  calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (country_code) REFERENCES countries_supported(country_code),
  UNIQUE (country_code, month)
);

-- Revenue Targets (Monthly/quarterly goals)
CREATE TABLE IF NOT EXISTS revenue_targets (
  id SERIAL PRIMARY KEY,
  target_period VARCHAR(20) NOT NULL, -- YYYY-MM (monthly) or Q1 2026 (quarterly)
  target_type VARCHAR(40), -- monthly / quarterly / annual

  -- Target Amounts
  target_revenue_ugx DOUBLE PRECISION NOT NULL,
  target_revenue_usd DOUBLE PRECISION,

  -- Target Breakdown
  target_barter_fees_ugx DOUBLE PRECISION,
  target_labor_fees_ugx DOUBLE PRECISION,
  target_facility_commissions_ugx DOUBLE PRECISION,

  -- Target Metrics
  target_transactions INTEGER,
  target_active_users INTEGER,
  target_countries INTEGER, -- How many countries should be active

  -- Actuals (Updated monthly)
  actual_revenue_ugx DOUBLE PRECISION DEFAULT 0,
  actual_transactions INTEGER DEFAULT 0,
  actual_active_users INTEGER DEFAULT 0,

  -- Achievement
  achievement_pct DOUBLE PRECISION, -- (actual / target) × 100
  is_achieved BOOLEAN DEFAULT FALSE,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (target_period)
);

-- Seed revenue targets (from plan: $23K/month by Month 12)
INSERT INTO revenue_targets (target_period, target_type, target_revenue_ugx, target_revenue_usd, target_transactions, target_active_users, target_countries) VALUES
-- Month 6 targets (MVP scale)
('2026-10', 'monthly', 11250000, 3000, 3000, 1500, 3), -- $3K/month, 1,500 barter traders + 500 labor providers
-- Month 12 targets (Full Phase 4 scale)
('2027-04', 'monthly', 86250000, 23000, 150000, 30000, 20), -- $23K/month, 10K barter traders + 5K labor + 20K facility
-- Month 24 targets (Scale to $230K/month)
('2028-04', 'monthly', 862500000, 230000, 1500000, 300000, 40), -- $230K/month, 100K barter + 50K labor
-- Quarter 1 2027 target (first full quarter after Phase 5)
('Q1 2027', 'quarterly', 172500000, 46000, 300000, 60000, 15); -- $46K/quarter

-- Revenue Forecast (Projected future revenue)
CREATE TABLE IF NOT EXISTS revenue_forecast (
  id SERIAL PRIMARY KEY,
  forecast_month DATE NOT NULL, -- YYYY-MM-01
  forecast_type VARCHAR(40) DEFAULT 'growth_projection', -- conservative / realistic / optimistic / growth_projection

  -- Forecasted Revenue
  forecasted_revenue_ugx DOUBLE PRECISION NOT NULL,
  forecasted_revenue_usd DOUBLE PRECISION,

  -- Assumptions
  assumed_barter_transactions INTEGER,
  assumed_labor_transactions INTEGER,
  assumed_avg_fee_ugx DOUBLE PRECISION,
  assumed_countries_active INTEGER,

  -- Confidence
  confidence_level VARCHAR(40), -- low / medium / high
  confidence_pct DOUBLE PRECISION, -- 0-100

  -- Basis
  forecast_basis TEXT, -- Historical trend / market research / competitor analysis / user growth rate

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (forecast_month, forecast_type)
);

-- Partner Payout Schedule (Track what we owe facility/pharmacy partners)
CREATE TABLE IF NOT EXISTS partner_payout_schedule (
  id SERIAL PRIMARY KEY,
  partner_type VARCHAR(40) NOT NULL, -- facility / pharmacy
  partner_id INTEGER NOT NULL,
  payout_month DATE NOT NULL, -- YYYY-MM-01

  -- Revenue Sharing
  total_revenue_generated_ugx DOUBLE PRECISION NOT NULL, -- Total revenue from this partner's transactions
  partner_commission_pct DOUBLE PRECISION NOT NULL, -- From facility_partners.commission_pct
  partner_payout_amount_ugx DOUBLE PRECISION NOT NULL, -- Amount we owe partner

  -- Payout Status
  payout_status VARCHAR(40) DEFAULT 'pending', -- pending / approved / paid / disputed
  payment_method VARCHAR(40), -- bank_transfer / mobile_money / afya_points
  payment_reference VARCHAR(200), -- Bank reference or mobile money transaction ID

  approved_by INTEGER, -- Staff ID who approved payout
  approved_at TIMESTAMP,
  paid_at TIMESTAMP,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (partner_id) REFERENCES facility_partners(id) ON DELETE CASCADE,
  FOREIGN KEY (approved_by) REFERENCES medical_staff(id) ON DELETE SET NULL,

  UNIQUE (partner_type, partner_id, payout_month)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_revenue_ledger_source ON platform_revenue_ledger(revenue_source);
CREATE INDEX IF NOT EXISTS idx_revenue_ledger_user ON platform_revenue_ledger(user_id);
CREATE INDEX IF NOT EXISTS idx_revenue_ledger_country ON platform_revenue_ledger(country_code);
CREATE INDEX IF NOT EXISTS idx_revenue_ledger_month ON platform_revenue_ledger(month);
CREATE INDEX IF NOT EXISTS idx_revenue_ledger_date ON platform_revenue_ledger(revenue_date);

CREATE INDEX IF NOT EXISTS idx_monthly_summary_month ON monthly_revenue_summary(month);

CREATE INDEX IF NOT EXISTS idx_country_summary_country ON country_revenue_summary(country_code);
CREATE INDEX IF NOT EXISTS idx_country_summary_month ON country_revenue_summary(month);

CREATE INDEX IF NOT EXISTS idx_revenue_targets_period ON revenue_targets(target_period);

CREATE INDEX IF NOT EXISTS idx_revenue_forecast_month ON revenue_forecast(forecast_month);

CREATE INDEX IF NOT EXISTS idx_partner_payout_partner ON partner_payout_schedule(partner_type, partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_payout_month ON partner_payout_schedule(payout_month);
CREATE INDEX IF NOT EXISTS idx_partner_payout_status ON partner_payout_schedule(payout_status);

-- View: Current Month Revenue Status
CREATE VIEW IF NOT EXISTS v_current_month_revenue AS
SELECT
  DATE(CURRENT_DATE, 'start of month') AS month,
  SUM(amount_ugx) AS total_revenue_ugx,
  SUM(CASE WHEN revenue_source = 'barter_transaction_fees' THEN amount_ugx ELSE 0 END) AS barter_fees_ugx,
  SUM(CASE WHEN revenue_source = 'labor_transaction_fees' THEN amount_ugx ELSE 0 END) AS labor_fees_ugx,
  SUM(CASE WHEN revenue_source = 'verification_fees' THEN amount_ugx ELSE 0 END) AS verification_fees_ugx,
  SUM(CASE WHEN revenue_source = 'premium_listing_fees' THEN amount_ugx ELSE 0 END) AS premium_fees_ugx,
  COUNT(*) AS total_transactions
FROM platform_revenue_ledger
WHERE month = DATE(CURRENT_DATE, 'start of month');

-- View: Top Revenue Countries (Current Month)
CREATE VIEW IF NOT EXISTS v_top_revenue_countries_current_month AS
SELECT
  cs.country_code,
  cs.country_name,
  SUM(prl.amount_ugx) AS total_revenue_ugx,
  COUNT(*) AS transaction_count
FROM platform_revenue_ledger prl
JOIN countries_supported cs ON prl.country_code = cs.country_code
WHERE prl.month = DATE(CURRENT_DATE, 'start of month')
GROUP BY cs.country_code, cs.country_name
ORDER BY total_revenue_ugx DESC
LIMIT 10;

-- View: Revenue vs Target (Current Month)
CREATE VIEW IF NOT EXISTS v_revenue_vs_target AS
SELECT
  rt.target_period,
  rt.target_revenue_ugx,
  rt.target_revenue_usd,
  rt.actual_revenue_ugx,
  rt.achievement_pct,
  rt.target_transactions,
  rt.actual_transactions,
  CASE
    WHEN rt.achievement_pct >= 100 THEN 'exceeded'
    WHEN rt.achievement_pct >= 80 THEN 'on_track'
    WHEN rt.achievement_pct >= 50 THEN 'at_risk'
    ELSE 'behind'
  END AS status
FROM revenue_targets rt
WHERE rt.target_period = strftime('%Y-%m', CURRENT_DATE);

-- Trigger: Log platform revenue when barter transaction completes
CREATE TRIGGER IF NOT EXISTS trg_log_barter_revenue
AFTER UPDATE OF status ON barter_exchange_transactions
FOR EACH ROW
WHEN NEW.status = 'completed' AND OLD.status = 'in_escrow'
BEGIN
  -- Log platform revenue (split fee: 1.75% per party = 3.5% total)
  INSERT INTO platform_revenue_ledger (
    revenue_source,
    amount_ugx,
    amount_ap,
    user_id,
    transaction_id,
    transaction_type,
    country_code,
    revenue_date,
    month,
    year
  )
  VALUES (
    'barter_transaction_fees',
    NEW.transaction_fee_ugx,
    NEW.transaction_fee_ap,
    NEW.party_a_user_id,
    NEW.id,
    'barter_exchange',
    (SELECT country_code FROM users WHERE id = NEW.party_a_user_id),
    DATE('now'),
    DATE('now', 'start of month'),
    CAST(strftime('%Y', 'now') AS INTEGER)
  );
END;

-- Trigger: Log platform revenue when labor hour verified
CREATE TRIGGER IF NOT EXISTS trg_log_labor_revenue
AFTER UPDATE OF is_verified ON labor_hour_ledger
FOR EACH ROW
WHEN NEW.is_verified = TRUE AND OLD.is_verified = FALSE
BEGIN
  INSERT INTO platform_revenue_ledger (
    revenue_source,
    amount_ugx,
    amount_ap,
    user_id,
    transaction_id,
    transaction_type,
    country_code,
    revenue_date,
    month,
    year
  )
  VALUES (
    'labor_transaction_fees',
    NEW.platform_revenue_ugx,
    NEW.transaction_fee_ap,
    NEW.user_id,
    NEW.id,
    'labor_booking',
    (SELECT country_code FROM users WHERE id = NEW.user_id),
    DATE('now'),
    DATE('now', 'start of month'),
    CAST(strftime('%Y', 'now') AS INTEGER)
  );
END;

-- Trigger: Update monthly revenue summary (lightweight update, full calc done by cron)
CREATE TRIGGER IF NOT EXISTS trg_update_monthly_summary
AFTER INSERT ON platform_revenue_ledger
FOR EACH ROW
BEGIN
  INSERT INTO monthly_revenue_summary (month, total_revenue_ugx, total_transactions)
  VALUES (NEW.month, NEW.amount_ugx, 1)
  ON CONFLICT(month) DO UPDATE SET
    total_revenue_ugx = total_revenue_ugx + NEW.amount_ugx,
    total_transactions = total_transactions + 1;
END;

-- Function: Calculate monthly revenue (documented for backend cron job)
/*
MONTHLY REVENUE CALCULATION (Backend cron runs on 1st of each month):

1. Aggregate platform_revenue_ledger by revenue_source for previous month
2. Calculate totals:
   - barter_fees = SUM(amount_ugx WHERE revenue_source = 'barter_transaction_fees')
   - labor_fees = SUM(amount_ugx WHERE revenue_source = 'labor_transaction_fees')
   - verification_fees = SUM(amount_ugx WHERE revenue_source = 'verification_fees')
   - escrow_fees = SUM(amount_ugx WHERE revenue_source = 'escrow_fees')
   - premium_fees = SUM(amount_ugx WHERE revenue_source = 'premium_listing_fees')
   - total_revenue = SUM(amount_ugx)

3. Calculate KPIs:
   - avg_revenue_per_transaction = total_revenue / total_transactions
   - achievement_pct = (actual_revenue / target_revenue) × 100

4. Update monthly_revenue_summary table

5. Generate country_revenue_summary (top revenue countries)

6. Update revenue_targets.actual_revenue_ugx

7. Generate partner_payout_schedule entries for facility/pharmacy partners

8. Alert if achievement_pct < 80% (at_risk status)

EXAMPLE CALCULATION (Month 12 - April 2027):
- Barter fees: 10,000 trades × 50,000 UGX avg × 3.5% = 17,500,000 UGX (~$4,700)
- Labor fees: 5,000 bookings × 100,000 UGX avg × 5% = 25,000,000 UGX (~$6,700)
- Premium listings: 500 users × 50,000 UGX (500 AP × 100) = 25,000,000 UGX (~$6,700)
- Facility commissions: 20,000 services × 100,000 UGX × 10% = 20,000,000 UGX (~$5,300)
= Total: 87,500,000 UGX (~$23,400/month) ✓ Target achieved!

SCALING PROJECTIONS:
- Month 6: 11M UGX ($3K/month) - 1,500 users, 3 countries
- Month 12: 86M UGX ($23K/month) - 30,000 users, 20 countries
- Month 24: 862M UGX ($230K/month) - 300,000 users, 40 countries
- Month 36: 8.6B UGX ($2.3M/month) - 3M users, 54 countries
*/
