-- Remove the retired barter, labour, and payment subsystem.
-- Historical migrations remain as an audit trail; this forward migration makes
-- both upgraded and newly provisioned PostgreSQL databases finish without it.

DROP TABLE IF EXISTS
    barter_escrow_locks,
    barter_exchange_transactions,
    barter_goods_catalog,
    barter_item_categories,
    barter_match_notifications,
    barter_match_scores,
    barter_services_catalog,
    barter_transaction_timeline,
    user_barter_preferences,
    labor_booking_requests,
    labor_currency_conversion,
    labor_demand_surge,
    labor_earnings_summary,
    labor_hour_ledger,
    labor_no_show_log,
    labor_services_registry,
    labor_skill_categories,
    labor_verification_queue,
    consultation_payments,
    facility_payment_acceptance,
    fee_structure_config,
    fee_waiver_log,
    hybrid_payment_approval_queue,
    hybrid_payment_details,
    payment_gateways_log,
    pharmacy_payment_acceptance,
    unified_payment_ledger,
    user_payment_preferences,
    currency_exchange_rates,
    universal_currency_matrix,
    cross_platform_currency_bridge,
    product_multi_currency_pricing,
    country_fee_adjustments,
    country_revenue_summary,
    monthly_revenue_summary,
    platform_revenue_ledger,
    revenue_forecast,
    revenue_targets,
    trust_actions_log,
    trust_score_weights,
    user_trust_ratings
CASCADE;
