-- Expand bootstrap stub tables for auth and gamification.
-- Safe to re-run (IF NOT EXISTS).

ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS country_code VARCHAR(5);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP;

ALTER TABLE avatar_stats ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE avatar_stats ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_subscriptions ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE user_subscriptions ADD COLUMN IF NOT EXISTS plan_id INTEGER DEFAULT 1;
ALTER TABLE user_subscriptions ADD COLUMN IF NOT EXISTS status VARCHAR(40) DEFAULT 'active';
ALTER TABLE user_subscriptions ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20) DEFAULT 'monthly';
ALTER TABLE user_subscriptions ADD COLUMN IF NOT EXISTS current_period_start DATE;
ALTER TABLE user_subscriptions ADD COLUMN IF NOT EXISTS current_period_end DATE;
