-- Expand bootstrap stub tables so seed CSV import can load nutrition data.
-- Safe to re-run (IF NOT EXISTS).

ALTER TABLE nutrients ADD COLUMN IF NOT EXISTS name VARCHAR(120);
ALTER TABLE nutrients ADD COLUMN IF NOT EXISTS symbol VARCHAR(20);
ALTER TABLE nutrients ADD COLUMN IF NOT EXISTS units VARCHAR(20);
ALTER TABLE nutrients ADD COLUMN IF NOT EXISTS category VARCHAR(60);

ALTER TABLE foods ADD COLUMN IF NOT EXISTS name VARCHAR(200);
ALTER TABLE foods ADD COLUMN IF NOT EXISTS local_name VARCHAR(200);
ALTER TABLE foods ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE foods ADD COLUMN IF NOT EXISTS glycemic_index DOUBLE PRECISION;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS is_local BOOLEAN DEFAULT TRUE;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS region_code VARCHAR(10);
ALTER TABLE foods ADD COLUMN IF NOT EXISTS scientific_name VARCHAR(200);
ALTER TABLE foods ADD COLUMN IF NOT EXISTS gi_classification VARCHAR(40);

ALTER TABLE food_nutrients ADD COLUMN IF NOT EXISTS food_id INTEGER;
ALTER TABLE food_nutrients ADD COLUMN IF NOT EXISTS nutrient_id INTEGER;
ALTER TABLE food_nutrients ADD COLUMN IF NOT EXISTS amount_per_100g DOUBLE PRECISION;

ALTER TABLE glycemic_load_index ADD COLUMN IF NOT EXISTS food_id INTEGER;
ALTER TABLE glycemic_load_index ADD COLUMN IF NOT EXISTS food_name VARCHAR(200);
ALTER TABLE glycemic_load_index ADD COLUMN IF NOT EXISTS glycemic_load DOUBLE PRECISION;
ALTER TABLE glycemic_load_index ADD COLUMN IF NOT EXISTS gl_category VARCHAR(40);

ALTER TABLE renal_acid_load_data ADD COLUMN IF NOT EXISTS food_id INTEGER;
ALTER TABLE renal_acid_load_data ADD COLUMN IF NOT EXISTS food_name VARCHAR(200);
ALTER TABLE renal_acid_load_data ADD COLUMN IF NOT EXISTS pral_value DOUBLE PRECISION;
ALTER TABLE renal_acid_load_data ADD COLUMN IF NOT EXISTS ckd_recommendation VARCHAR(40);

ALTER TABLE meals ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS meal_type VARCHAR(40);
ALTER TABLE meals ADD COLUMN IF NOT EXISTS meal_date DATE;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE meal_components ADD COLUMN IF NOT EXISTS meal_id INTEGER;
ALTER TABLE meal_components ADD COLUMN IF NOT EXISTS food_id INTEGER;
ALTER TABLE meal_components ADD COLUMN IF NOT EXISTS quantity_grams DOUBLE PRECISION;
ALTER TABLE meal_components ADD COLUMN IF NOT EXISTS meal_component_type VARCHAR(40) DEFAULT 'main';

ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS meal_id INTEGER;
ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS calories_total DOUBLE PRECISION;
ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS protein_g_total DOUBLE PRECISION;
ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS potassium_mg_total DOUBLE PRECISION;
ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS phosphorus_mg_total DOUBLE PRECISION;
ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS pral_total DOUBLE PRECISION;
ALTER TABLE meal_nutrition_calculations ADD COLUMN IF NOT EXISTS calculated_at TIMESTAMP;
